language: python
services: docker
cache: pip

branches:
  except:
    - /^v[0-9]/

matrix:
  include:
  - python: "3.7"
  - python: "3.8"
  - python: "3.9"

before_install:
  - image="openhab/openhab:latest-alpine"

install:
  - pip install -U pip
  - pip install --upgrade-strategy eager .[test]
  - docker run -d --name openhab -p 8080:8080 -e OPENHAB_HTTP_PORT=8080 -v $TRAVIS_BUILD_DIR/docker/openhab_conf:/openhab/conf -v $TRAVIS_BUILD_DIR/docker/openhab_userdata:/openhab/userdata $image
  - python docker/test_connectivity.py

script:
  - pytest -v tests
